### ISSUE TITLE
Simple math problems produce errors

### ISSUE THREAD

**Issue by robertpiazza** [ischlag/TP-Transformer#1]
Using the google colab environment, entering simple queries such gives incorrect answers such as "Calculate the sum of 3/5 and 2/7" produces ['<sos>1/5<eos>']
terminal.enter("What is 0.6 + 2/9") produces ['<sos>12/9<eos>']
terminal.enter("(3/2)+(3/8)") produces ['<sos>9/8<eos>']
terminal.enter("1.5-(3/8)") produces ['<sos>-7/8<eos>']

Perhaps this is an artifact of not enough simple problems in the training dataset?

**Comment by ischlag** [comment]
Hi Robert

What you observe is certainly the case but not too surprising for a machine learning model. Just because the model is capable of solving many hard problems does not imply that it will be flawless for all possible simple problems. As you recognised, it is not too hard to produce results which are clearly wrong. 

That said, some of your queries are of out of distribution which makes generalizing to it more challenging. When it comes to arithmetic the network only has a handful of modules to learn from. Those tend to follow a clear format: 

`Calculate 39/26*(-3)/(-15)*-1.` -> `-3/10`
`What is ((100/45)/5)/(-2)?` -> `-2/9`
`5/(-10)*-5*(-4)/130` -> `-1/13`

So a few thoughts:
1.) I think that no module combines fractions with decimal numbers which means that there could be representational differences between the two. Which means that the model cannot combine them because it has not learned to do so, ever. 

2.) A similar thought I have is due to "Calculate the sum of" which is kind of out of distribution. I'm not even sure the network has ever learned something like "and". The easiest way of messing with the prediction of the model is in changing the things we humans are invariant to: filler words, spaces between the characters, punctuation, etc. The network is not trained to be resilient to such "noise". Here is an example:
`5/(-10) * -5 * (-4)/130` will now wrongly result in `-11/6` ... but all we did is add a few empty spaces.

3.) On the other hand, sometimes the structure is crucial: `(3/2) + (3/8)` (instead of `(3/2)+(3/8)`) will correctly produce `15/8`. This might not make sense on a human level but it is not unreasonable since the model could learn to use the additional computational resources which are introduced by the empty spaces. Sometimes that might just through it off.

Finally, I'd like to mention that the point of training a neural network on this math dataset is to test its generalisation capability in such a difficult setting. It would be unreasonable to use such a model to evaluate such expressions.

**Comment by robertpiazza** [comment]
Thank you for the excellent overview and in-depth explanations! It truly is a difficult environment to get such a high degree of generalization and your implementation of the architecture shows a large potential for the field. 
In the near term, I saw this in a business context as being presented as a competitor to tools such as Mathematica or wolfram alpha. If that was a direction MS was interested in, perhaps it would be worth performing data augmentation on the original deepmind dataset to create the kind of tricky examples you suggested above such as adding spaces and substituting words for symbols. 
Thanks again for your insights and I'll close this issue.

**Comment by ischlag** [comment]
@robertpiazza You might be interested in this work where they directly compare with Mathematica and Matlab:

https://openreview.net/forum?id=S1eZYeHFDS
https://arxiv.org/abs/1912.01412 (the same on arxiv)
